### ISSUE TITLE
Planned Features

### ISSUE THREAD

**Issue by jtmcgrath** [jtmcgrath/harmony#4]
Re: Discord customisations shared by Mark ([gist here](https://gist.github.com/markerikson/cfb422d030cf450e8a94)):

- [ ] Allow text selection
- [ ] Various fixes
- [ ] Font size customisation
- [ ] Sizing tweaks
- [ ] User Settings only in account section
- [ ] Hide voice channels

**Comment by thisRaptori** [comment]
Note for hiding voice channels:
```css
svg[name="Speaker"],
svg[name="Speaker"] + * {
    display: none;
}
```
